import { useEffect, useState } from "react";
import API from "../api/api";

function History() {
  const [history, setHistory] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    fetchHistory();
  }, []);

  const fetchHistory = async () => {
    try {
      const res = await API.get("/prediction/prediction/history");
      setHistory(res.data);
    } catch (error) {
      console.log(error);
    }
  };

  const filteredHistory = history.filter((item) =>
    item.prediction.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="container mt-5">

      {/* Heading */}
      <div className="text-center mb-4">
        <h1 className="text-success">
          📜 Prediction History
        </h1>

        <p className="text-muted">
          View all renewable energy predictions generated by the AI model.
        </p>
      </div>

      {/* Statistics */}
      <div className="row mb-4">

        <div className="col-md-4">
          <div className="card shadow text-center bg-primary text-white">
            <div className="card-body">
              <h2>{history.length}</h2>
              <h5>Total Predictions</h5>
            </div>
          </div>
        </div>

        <div className="col-md-4">
          <div className="card shadow text-center bg-success text-white">
            <div className="card-body">
              <h2>
                {history.filter(h => h.prediction === "Solar").length}
              </h2>
              <h5>Solar Predictions</h5>
            </div>
          </div>
        </div>

        <div className="col-md-4">
          <div className="card shadow text-center bg-warning">
            <div className="card-body">
              <h2>
                {history.filter(h => h.prediction === "Wind").length}
              </h2>
              <h5>Wind Predictions</h5>
            </div>
          </div>
        </div>

      </div>

      {/* Search */}
      <div className="mb-4">
        <input
          type="text"
          className="form-control"
          placeholder="🔍 Search Prediction..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {/* History Table */}
      <div className="card shadow">

        <div className="card-header bg-dark text-white">
          Prediction Records
        </div>

        <div className="card-body">

          <div className="table-responsive">

            <table className="table table-hover table-bordered">

              <thead className="table-success">

                <tr>
                  <th>ID</th>
                  <th>Temperature</th>
                  <th>Wind Speed</th>
                  <th>Humidity</th>
                  <th>Rainfall</th>
                  <th>Prediction</th>
                  <th>Date</th>
                </tr>

              </thead>

              <tbody>

                {filteredHistory.map((item) => (

                  <tr key={item.id}>

                    <td>{item.id}</td>

                    <td>{item.temperature} °C</td>

                    <td>{item.wind_speed} km/h</td>

                    <td>{item.humidity}%</td>

                    <td>{item.rainfall} mm</td>

                    <td>

                      <span
                        className={
                          item.prediction === "Solar"
                            ? "badge bg-warning text-dark"
                            : "badge bg-primary"
                        }
                      >
                        {item.prediction}
                      </span>

                    </td>

                    <td>
                      {new Date(item.created_at).toLocaleString()}
                    </td>

                  </tr>

                ))}

              </tbody>

            </table>

          </div>

        </div>

      </div>

      {/* Footer */}
      <div className="text-center mt-5">
        <p className="text-muted">
          AI-Based Renewable Energy Recommendation System
        </p>
      </div>

    </div>
  );
}

export default History;